/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
    './.storybook/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Buttons
        'btn-primary':       'var(--surface-action-primary)',
        'btn-hover-primary': 'var(--surface-action-hover-primary)',
        'btn-secondary':     'var(--surface-action-secondary)',
        'btn-hover-sec':     'var(--surface-action-hover-secondary)',
        'btn-inverse':       'var(--surface-action-inverse)',
        'btn-disabled':      'var(--surface-disabled-dark)',
        'btn-on-primary':    'var(--text-action-on-primary)',
        'btn-on-secondary':  'var(--text-action-on-secondary)',
        'btn-on-tertiary':   'var(--text-action-on-tertiary)',
        'btn-text-inverse':  'var(--text-action-inverse)',
        'btn-text-active':   'var(--text-action-active)',
        'btn-text-disabled': 'var(--text-action-disabled)',
        'btn-border':        'var(--border-primary)',
        'btn-border-dis':    'var(--border-disabled)',
        // Fields
        'field-bg':           'var(--surface-secondary)',
        'field-bg-focus':     'var(--surface-page)',
        'field-bg-disabled':  'var(--surface-disabled-dark)',
        'field-bg-error':     'var(--surface-error-light)',
        'field-bg-success':   'var(--surface-positive-light)',
        'field-border':       'var(--border-passive)',
        'field-border-error': 'var(--border-error)',
        'field-border-ok':    'var(--border-positive)',
        'field-border-dis':   'var(--border-disabled)',
        'field-text':         'var(--text-body)',
        'field-label':        'var(--text-passive)',
        'field-error':        'var(--text-error)',
        'field-disabled':     'var(--text-disabled)',
        'field-success':      'var(--text-success)',
        'field-icon-error':   'var(--icon-error)',
        'field-icon-success': 'var(--icon-positive)',
        // Cards
        'card-bg':   'var(--surface-brand-primary)',
        'card-text': 'var(--text-inverse)',
        // Page & Drawer
        'page-bg':      'var(--surface-page)',
        'drawer-bg':    'var(--surface-secondary)',
        'overlay':      'var(--surface-overlay-background)',
        'text-heading': 'var(--text-headings)',
        'text-body':    'var(--text-body)',
        'text-brand':   'var(--text-brand)',
        'text-passive': 'var(--text-passive)',
        'text-inverse': 'var(--text-inverse)',
      },
      borderRadius: {
        'btn':    'var(--border-radius-round)',
        'field':  'var(--border-radius-sm)',
        'card':   'var(--border-radius-lg)',
        'drawer': 'var(--border-radius-md)',
      },
      borderWidth: {
        'sm': 'var(--border-sm)',
        'md': 'var(--border-md)',
      },
      fontFamily: {
        body:    ['var(--font-family-body)'],
        heading: ['var(--font-family-heading)'],
      },
      fontSize: {
        'xs':        ['var(--font-size-body-xs)',    { lineHeight: 'var(--line-height-body-sm)' }],
        'sm':        ['var(--font-size-body-sm)',    { lineHeight: 'var(--line-height-body-sm)' }],
        'base':      ['var(--font-size-body-md)',    { lineHeight: 'var(--line-height-body-md)' }],
        'lg':        ['var(--font-size-body-lg)',    { lineHeight: '1.5' }],
        'h6':        ['var(--font-size-heading-h6)', { lineHeight: '1.4' }],
        'h5':        ['var(--font-size-heading-h5)', { lineHeight: '1.4' }],
        'h4':        ['var(--font-size-heading-h4)', { lineHeight: '1.4' }],
        'action-sm': ['var(--font-size-action-sm)',  { lineHeight: '1' }],
        'action-md': ['var(--font-size-action-md)',  { lineHeight: '1' }],
      },
      spacing: {
        '2xs': 'var(--spacing-2xs)',
        'xs':  'var(--spacing-xs)',
        'sm':  'var(--spacing-sm)',
        'md':  'var(--spacing-md)',
        'lg':  'var(--spacing-lg)',
        'xl':  'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
      },
    },
  },
  plugins: [],
};