/**
 * Token Build — Style Dictionary v5
 * Run: node tokens/build.mjs
 */

import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(readFileSync(join(__dirname, 'figma-tokens.json'), 'utf8'));

// ── 1. Per-brand merge ────────────────────────────────────────────────────
// figma-tokens.json has a 3-layer architecture:
//   Primitives/Default       ← raw hex/px values
//   Alias colours/BrandX     ← semantic aliases (Primary, Error...)
//   Mapped/BrandX            ← component-intent (Surface.Action.Primary...)
//
// We merge per brand into one object so Style Dictionary resolves
// all {cross-layer references} natively — no manual resolver needed.

function deepMerge(target, source) {
  for (const [key, val] of Object.entries(source)) {
    if (val && typeof val === 'object' && !val.value && !Array.isArray(val)) {
      target[key] = target[key] || {};
      deepMerge(target[key], val);
    } else {
      target[key] = val;
    }
  }
}

function mergeForBrand(brand) {
  const merged = {};
  for (const setName of [
    'Primitives/Default',
    `Alias colours/${brand}`,
    `Mapped/${brand}`,
    'Responsive/Desktop',
  ]) {
    if (raw[setName]) deepMerge(merged, raw[setName]);
  }
  return merged;
}

// ── 2. Component token filter ─────────────────────────────────────────────
// Only emit tokens the 5 challenge components actually need.
// Paths map to the Mapped/* layer keys.

const COMPONENT_TOKENS = new Set([
  'Surface.Colour.Action.Primary',
  'Surface.Colour.Action.Hover-Primary',
  'Surface.Colour.Action.Secondary',
  'Surface.Colour.Action.Hover-Secondary',
  'Surface.Colour.Action.Inverse',
  'Surface.Colour.Action.Inverse-Darker',
  'Surface.Colour.Disabled-Dark',
  'Surface.Colour.Secondary',
  'Surface.Colour.Page',
  'Surface.Colour.Error Light',
  'Surface.Colour.Positive Light',
  'Surface.Colour.Overlay-background',
  'Surface.Colour.Brand Primary',
  'Text.Colour.Action.Active',
  'Text.Colour.Action.Inverse',
  'Text.Colour.Action.OnPrimary',
  'Text.Colour.Action.OnSecondary',
  'Text.Colour.Action.OnTertiary',
  'Text.Colour.Action.Disabled',
  'Text.Colour.Body',
  'Text.Colour.Headings',
  'Text.Colour.Brand',
  'Text.Colour.Passive',
  'Text.Colour.Error',
  'Text.Colour.Disabled',
  'Text.Colour.Success',
  'Text.Colour.Inverse',
  'Icon.Colour.Error',
  'Icon.Colour.Positive',
  'Border.Colour.Primary',
  'Border.Colour.Passive',
  'Border.Colour.Disabled',
  'Border.Colour.Inverse',
  'Border.Colour.Error',
  'Border.Colour.Positive',
  'Border.Colour.Action.Active',
  'Border.Radius.Xs',
  'Border.Radius.Sm',
  'Border.Radius.Md',
  'Border.Radius.Lg',
  'Border.Radius.Round',
  'Border.Width.Sm',
  'Border.Width.Md',
  'Font-size.Body.Xs',
  'Font-size.Body.Sm',
  'Font-size.Body.Md',
  'Font-size.Body.Lg',
  'Font-size.Heading.H4',
  'Font-size.Heading.H5',
  'Font-size.Heading.H6',
  'Font-size.Action.Sm',
  'Font-size.Action.Md',
  'Line-height.Body.Sm',
  'Line-height.Body.Md',
  'Spacing.2xs',
  'Spacing.Xs',
  'Spacing.Sm',
  'Spacing.Md',
  'Spacing.Lg',
  'Spacing.Xl',
  'Spacing.2xl',
  'Spacing.3xl',
]);

// ── 3. Custom name transform ──────────────────────────────────────────────
// ['Surface','Colour','Action','Primary'] → 'surface-action-primary'
// Drops noisy grouping words (Colour, Width).

const STRIP_WORDS = new Set(['Colour', 'Width']);

function toKebab(str) {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .replace(/[^a-zA-Z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

// ── 4. Custom CSS format — [data-theme] scoped ────────────────────────────

function themedCSSFormat({ dictionary, options }) {
  const { brand, selector, fontBody, fontHeading } = options;
  const header = [
    `/**`,
    ` * ${brand} Design Tokens`,
    ` * Auto-generated by Style Dictionary — do not edit directly.`,
    ` * Source: tokens/figma-tokens.json`,
    ` */`,
  ].join('\n');

  const vars = dictionary.allTokens
    .map(t => `  --${t.name}: ${t.$value ?? t.value};`)
    .join('\n');

  const fontVars = [
    `  --font-family-body: '${fontBody}', sans-serif;`,
    `  --font-family-heading: '${fontHeading}', sans-serif;`,
  ].join('\n');

  return `${header}\n\n${selector} {\n${vars}\n${fontVars}\n}\n`;
}

// ── 5. Build ──────────────────────────────────────────────────────────────

async function buildBrand(brand) {
  const themeName   = brand === 'BrandA' ? 'brand-a' : 'brand-b';
  const primitives  = raw['Primitives/Default'];
  const fontBody    = primitives.Font.Brand[brand]['Font family'].Body.value;
  const fontHeading = primitives.Font.Brand[brand]['Font family'].Heading.value;

  const sd = new StyleDictionary({
    tokens: mergeForBrand(brand),
    hooks: {
      filters: {
        'component-only': (token) => COMPONENT_TOKENS.has(token.path.join('.')),
      },
      transforms: {
        'name/component-kebab': {
          type: 'name',
          transform: (token) =>
            token.path.filter(p => !STRIP_WORDS.has(p)).map(toKebab).join('-'),
        },
        'value/px-if-number': {
          type: 'value',
          filter: (token) => token.type === 'number' || token.$type === 'number',
          transform: (token) => {
            const v = token.$value ?? token.value;
            return typeof v === 'number' ? `${v}px` : v;
          },
        },
      },
      formats: {
        'css/themed': themedCSSFormat,
      },
    },
    platforms: {
      css: {
        transforms: ['name/component-kebab', 'color/css', 'value/px-if-number'],
        files: [{
          destination: `tokens/output/${themeName}.css`,
          format: 'css/themed',
          filter: 'component-only',
          options: { brand, selector: `[data-theme="${themeName}"]`, fontBody, fontHeading },
        }],
      },
    },
  });

  await sd.init();
  await sd.buildAllPlatforms();
}

await buildBrand('BrandA');
await buildBrand('BrandB');

writeFileSync(join(__dirname, 'output/tokens.css'), [
  '/* Combined brand tokens — import in your app entry point */',
  "@import './brand-a.css';",
  "@import './brand-b.css';",
  '',
].join('\n'));

console.log('\n✅ Style Dictionary build complete:');
console.log('   tokens/output/brand-a.css');
console.log('   tokens/output/brand-b.css');